name: Security Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  security-audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar análisis de seguridad con npm audit
        run: npm audit --audit-level=high
